DSParserBundle:
  models: (optional)
    source: DS\ParserBundle\Model\Source
    link: DS\ParserBundle\Model\Link
    entity: DS\ParserBundle\Model\Entity (optional)

  parser:
    google:
     - type: link
       name: link (google.link.parser service) optional same as type
       model: DS\ParserBundle\Parser\LinkInterface
     - type: mixed
       name: custom (google.custom.parser service)
       model: DS\ParserBundle\Parser\ContentInterface + LinkInterface
     - type: content
       model: DS\ParserBundle\Parser\ContentInterface

  scanner:
      default_model: DS\ParserBundle\Scanner\Default
      sources:
        google:
          model: DS\ParserBundle\Scanner\MyCustom
          parser: @google.link.parser or @google.mixed.parser by default
          expiration: 1d
          urls:
            - catalog.google.com
            - google.com
            - web.google.com
          validation:
            product:
              condition: h1 > b > li > test = "Specification"
              validator: DS\ParserBundle\Validator\MyCustom
            category:
              condition: h1 > text = "Category"
        tut:
          expiration: 1d

  entity_manager:
    default_model: DS\ParserBundle\EntityManager\Default
    entity:
      product:
        - source: google
          parser: @google.content.parser (default) or @google.mixed.parser
          output: array (ArrayMapper) entity (EntityMapper)
          mapper: DS\ParserBundle\Mapper\Default (optional)
          entity_class: You\Custom\EntityClass (require for entity output type)
          cache: true
          condition: (require, optional if custom mapper exist)
            id:
              value: h1 > body > class op
              default: exception
            name:
              value: h1 > body > class name
              default: false
            title:
              value: h1 > class title